apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-loader
  labels:
    app.kubernetes.io/name: data-loader
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: data-loader
  template:
    metadata:
      labels:
        app.kubernetes.io/name: data-loader
    spec:
      containers:
        - name: data-loader
          image: docker.io/edsandovalhz/python-data-loader
          env:
          - name: HZ_ENDPOINT
            value: "hz-python-hazelcast:5701"
---

apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: fraud-dashboard
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: fraud-dashboard
  ports:
    - name: http
      protocol: TCP
      port: 8501
      targetPort: fb-port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-dashboard
  labels:
    app.kubernetes.io/name: fraud-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fraud-dashboard
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fraud-dashboard
    spec:
      containers:
        - name: fraud-dashboard
          image: docker.io/edsandovalhz/python-sql-fraud-dashboard
          ports:
            - name: fb-port
              containerPort: 8501
              protocol: TCP
          env:
          - name: HZ_ONNX
            value: "hz-python-hazelcast:5701"

