image:
  repository: edsandovalhz/hz-531-python-310
  tag: latest
  pullPolicy: Always

cluster:
  memberCount: 3
topologySpreadConstraints:
- maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: ScheduleAnyway
  labelSelector:
    matchLabels:
      "app.kubernetes.io/instance": hz-python

hazelcast:
  #loggingLevel: DEBUG
  yaml:
    hazelcast:
      partition-group:
        enabled: true
        group-type: NODE_AWARE
      cluster-name: dev
      map:
        predictionResult:
          eviction:
            size: 200000
            eviction-policy: LFU
            max-size-policy: PER_NODE
          partition-strategy: com.hazelcast.partition.strategy.StringAndPartitionAwarePartitioningStrategy
          indexes:
            - type: HASH
              attributes:
                - "customer_name"
            - type: HASH
              attributes:
                - "customer_city"
            - type: SORTED
              attributes:
                - "fraud_probability"
            - type: SORTED
              attributes:
                - "amount"
              attributes:
                - "customer_age_group"
            - type: HASH
              attributes:
                - "customer_gender"
        customers:
          partition-strategy: com.hazelcast.partition.strategy.StringAndPartitionAwarePartitioningStrategy
      network: 
        join:   
          kubernetes:
            enabled: true
            service-per-pod-label-name: com.hazelcast/external-access
            service-per-pod-label-value: "true"
      jet:
        enabled: true
        resource-upload-enabled: true

service:
  type: "LoadBalancer"

securityContext:
  readOnlyRootFilesystem: false
  

externalAccess:
  enabled: true
  service:
    labels:
      com.hazelcast/external-access: "true"

initContainers:
  - name: wait-for-lb
    image: bitnami/kubectl:1.22
    env:
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
    command:
      - "sh"
      - "-c"
    args:
      - until [ -n "$$(kubectl get svc -n $${POD_NAMESPACE} -l com.hazelcast/external-access="true" -ojsonpath="{.items[?(@.spec.selector.statefulset\.kubernetes\.io/pod-name==\"$${POD_NAME}\")].status.loadBalancer.ingress[0].ip}")" ]; do sleep 8; done
      