hazelcast:
  jet:
    enabled: true
    resource-upload-enabled: true
  network:
    rest-api:
      enabled: true
  map:
    predictionResult:
      partition-strategy: com.hazelcast.partition.strategy.StringAndPartitionAwarePartitioningStrategy
    customers:
      partition-strategy: com.hazelcast.partition.strategy.StringAndPartitionAwarePartitioningStrategy
    streaming-features:
      partition-strategy: com.hazelcast.partition.strategy.StringAndPartitionAwarePartitioningStrategy
